name: tda-dev
dependencies:
- python=3
- cython
- pandas
- requests
- pylint
- spyder
- openpyxl
- xlrd
- xlsxwriter
- matplotlib
- scikit-learn
- plotly
- r
- r-essentials
- pytest
- pytest-cov
- twine

- pip:
  - python-dotenv
  - -e git+https://github.com/tidepool-org/data-analytics#egg=tidals\&subdirectory=tidepool-analysis-tools
